version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "MlOpsBdeo-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-91g495dkoya3"
s3_prefix = "MlOpsBdeo-dev"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
image_repositories = [
    "ModelFunction=511901827322.dkr.ecr.eu-west-3.amazonaws.com/mlopsbdeodevf999a677/triggeredfunction2d3710dcrepo"
]
parameter_overrides = [
    "Env=dev"
]





[main]
[main.deploy]
[main.deploy.parameters]
stack_name = "MlOpsBdeo-main"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-91g495dkoya3"
s3_prefix = "MlOpsBdeo-main"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"main\""
image_repositories = ["ModelFunction=511901827322.dkr.ecr.eu-west-3.amazonaws.com/mlopsbdeomainc3445947/modelfunction645e79derepo"]
