version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MlOpsBdeo-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-91g495dkoya3"
s3_prefix = "MlOpsBdeo-dev"
region = "eu-west-3"
profile = "prueba"
capabilities = "CAPABILITY_IAM"
image_repositories = [
    "ModelFunction=511901827322.dkr.ecr.eu-west-3.amazonaws.com/mlopsbdeodevf999a677/triggeredfunction2d3710dcrepo"
]
parameter_overrides = [
    "Env=dev"
]