name: Pytest & Sonar
on:
  pull_request:
    branches:
      - dev
      - test
      - master
jobs:
  coverage:
    runs-on:
      - ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      # Dependencies
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependenciess
        run: |
          python3 -m pip install pytest
          python3 -m pip install flake8
          python3 -m pip install -r ./function/requirements.txt
          python3 -m pip install pytest-cov

      # Test
      - name: Test with pytest
        run: |
          pytest tests/unit/test_handler.py --doctest-modules --junitxml=junit/test-results.xml --cov=./ --cov-report=term-missing:skip-covered


      # Sonar Qube
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

